spring:
    profiles: puskai
    datasource:
        url: "jdbc:mysql://localhost:3306/pets?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
        username: root
        password: 
    jpa:
        show-sql: false
